name: Link checker

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '*.md'
      - '*.html'
      - '**/*.md'
      - '**/*.html'
      - '.github/workflows/link-checker.yml'
  pull_request:
    branches:
      - master
    paths:
      - '*.md'
      - '*.html'
      - '**/*.md'
      - '**/*.html'
      - '.github/workflows/link-checker.yml'
  schedule:
    - cron: "00 3 * * 1-5"

jobs:
  test:
    uses: vespa-engine/gh-actions/.github/workflows/jekyll-link-checker.yml@main
    with:
      ignore-files: |-
        /playground/index.html/
      ignore-urls: |-
        /localhost:8080/
        /docs.vespa.ai/playground/
        /javadoc.io.*#/
        /readthedocs.io.*#/
        /linux.die.net/
        /arxiv.org/
        /hub.docker.com/r/
        /platform.openai.com/
        /www.ietf.org/
        /search.maven.org/
