name: Verify Guides (Small)

on:
  workflow_dispatch: # Allow manual triggering of this workflow.

  push:
    branches: ["master"]
    paths:
      - '*.md'
      - '*.html'
      - '**/*.md'
      - '**/*.html'
      - '.github/workflows/verify-guides.yml' # Reusable workflow
      - '.github/workflows/verify-guides-small.yml' # This workflow

  pull_request:
    branches: ["master"]
    paths:
      - '*.md'
      - '*.html'
      - '**/*.md'
      - '**/*.html'
      - '.github/workflows/verify-guides.yml' # Reusable workflow
      - '.github/workflows/verify-guides-small.yml' # This workflow

jobs:
  small:
    uses: ./.github/workflows/verify-guides.yml
    with:
      test-config-path: "test/_test_config.yml"
