name: Verify Guides (Large)

on:
  workflow_dispatch: # Allow manual triggering of this workflow.

  push:
    branches: ["master"]
    paths:
      - 'en/tutorials/**/*'
      - '.github/workflows/verify-guides.yml' # Reusable workflow
      - '.github/workflows/verify-guides-large.yml' # This workflow

  pull_request:
    branches: ["master"]
    paths:
      - 'en/tutorials/**/*'
      - '.github/workflows/verify-guides.yml' # Reusable workflow
      - '.github/workflows/verify-guides-large.yml' # This workflow

jobs:
  large:
    uses: ./.github/workflows/verify-guides.yml
    with:
      test-config-path: "test/_test_config-large.yml"
